n=str(input("hey whats your name?? "))
p=str(input("where do you live?? "))
q=str(input("is this place in south mumbai?? "))
print("if yes then",p,"is a good place to live in ")
a=int(input("whats your age bruh??: "))
d=float(input("oh i see!! so you are an adult right?? what is the age of consent in india???: "))
print(type(n)) #tells us the data type of the variable that we put in the round brackets after type()
print(type(a))
print(type(d))
ls=[10,100,1000,10000]
print(type(ls))
print(type(ls[1]))
es=bool('')
print(es,type(es))